lib: [
  "_build/install/default/lib/Python/Lib/ast.ml" {"Lib/ast.ml"}
  "_build/install/default/lib/Python/Lib/interpret.ml" {"Lib/interpret.ml"}
  "_build/install/default/lib/Python/Lib/parser.ml" {"Lib/parser.ml"}
  "_build/install/default/lib/Python/Lib/python_Lib.a" {"Lib/python_Lib.a"}
  "_build/install/default/lib/Python/Lib/python_Lib.cma" {"Lib/python_Lib.cma"}
  "_build/install/default/lib/Python/Lib/python_Lib.cmi" {"Lib/python_Lib.cmi"}
  "_build/install/default/lib/Python/Lib/python_Lib.cmt" {"Lib/python_Lib.cmt"}
  "_build/install/default/lib/Python/Lib/python_Lib.cmx" {"Lib/python_Lib.cmx"}
  "_build/install/default/lib/Python/Lib/python_Lib.cmxa" {"Lib/python_Lib.cmxa"}
  "_build/install/default/lib/Python/Lib/python_Lib.ml" {"Lib/python_Lib.ml"}
  "_build/install/default/lib/Python/Lib/python_Lib__Ast.cmi" {"Lib/python_Lib__Ast.cmi"}
  "_build/install/default/lib/Python/Lib/python_Lib__Ast.cmt" {"Lib/python_Lib__Ast.cmt"}
  "_build/install/default/lib/Python/Lib/python_Lib__Ast.cmx" {"Lib/python_Lib__Ast.cmx"}
  "_build/install/default/lib/Python/Lib/python_Lib__Interpret.cmi" {"Lib/python_Lib__Interpret.cmi"}
  "_build/install/default/lib/Python/Lib/python_Lib__Interpret.cmt" {"Lib/python_Lib__Interpret.cmt"}
  "_build/install/default/lib/Python/Lib/python_Lib__Interpret.cmx" {"Lib/python_Lib__Interpret.cmx"}
  "_build/install/default/lib/Python/Lib/python_Lib__Parser.cmi" {"Lib/python_Lib__Parser.cmi"}
  "_build/install/default/lib/Python/Lib/python_Lib__Parser.cmt" {"Lib/python_Lib__Parser.cmt"}
  "_build/install/default/lib/Python/Lib/python_Lib__Parser.cmx" {"Lib/python_Lib__Parser.cmx"}
  "_build/install/default/lib/Python/META"
  "_build/install/default/lib/Python/dune-package"
  "_build/install/default/lib/Python/opam"
]
libexec: [
  "_build/install/default/lib/Python/Lib/python_Lib.cmxs" {"Lib/python_Lib.cmxs"}
]
bin: [
  "_build/install/default/bin/REPL"
  "_build/install/default/bin/demo_fact"
]
doc: [
  "_build/install/default/doc/Python/README.md"
]
